### ISSUE TITLE
real full text search

### ISSUE THREAD

**Issue by pajooh** [peopledoc/django-generic-filters#30]
why you don't use [search](https://docs.djangoproject.com/en/1.8/ref/models/querysets/#search) lookup for full-text search?
currently, just Mysql is supported (for a Postgresql implementation, [django-pg-fts](https://github.com/dvdmgl/django-pg-fts) can be used)

**Comment by Natim** [comment]
Do you have one for sqlite3 support? For now we are using both postgresql and sqlite3 database.

Feel free to send a Pull Request to implement the search module if you need it for MySQL.

**Comment by tmartinfr** [comment]
@pajooh We don't plan to implement this because we prefer to keep generic DB code for now. Would you agree to close this issue?

**Comment by tmartinfr** [comment]
@pajooh I close, re-open it if necessary !

**Comment by tmartinfr** [comment]
Sorry I misunderstood your issue. I'm putting some comment in the corresponding PR.

**Comment by ewjoachim** [comment]
The `__search` lookup has been deprecated:
https://docs.djangoproject.com/en/1.11/releases/1.10/#search-query-lookup

I'll be closing this issue if it's ok with everyone. Reopen if not.

Thanks for the suggestion, tough !
