### ISSUE TITLE
Replace bunch

### ISSUE THREAD

**Issue by jayvdb** [peopledoc/django-generic-filters#61]
Re #49 ,

bunch should be replaced with an alternative, such as https://pypi.org/project/python-box/

Please see https://github.com/dsc/bunch/issues .  Distros have dropped it, because it fails its own test suite on Python 3.

**Comment by ewjoachim** [comment]
I see https://github.com/Infinidat/munch / https://pypi.org/project/munch/, a fork that seems to work identically to bunch except it's maintained.

Would this fit your need ?

**Comment by jayvdb** [comment]
Yup.  It is already packaged by distros.

**Comment by ewjoachim** [comment]
Do you want to make the PR ? Or would you rather we do it ?

**Comment by jayvdb** [comment]
I'm not an active user; just going through packages on my radar which use it, so I can package them for openSUSE when they are released and fixed.

**Comment by ewjoachim** [comment]
It's a good thing you opened this issue.
I just realized that thanks to this line:
https://github.com/peopledoc/django-generic-filters/blob/c7581724235da560f2e570dd87e217a281eb11df/demo/setup.py#L20

we've never actually tested for django >= 2, let alone 3.

Time to sanitize all this.

**Comment by jayvdb** [comment]
> This, children, is why you should never pin your dependencies unless you have a very strong reason to

I've almost given up trying to tell people that pinning is in general a bad idea in source repos.  Seems pinning is all the rage now, esp in Python land.

Lots of caveats of course, but for OSS projects, letting new versions of deps smack you in the face with CI failures seems much more likely to result in interoperability across the ecosystem.

**Comment by ewjoachim** [comment]
https://pypi.org/project/django-generic-filters/2.0.0/ :)
